import {
  FOUC_PREVENTION_SCRIPT,
  ThemeProvider,
} from "@notebooklm/ui/components/ThemeProvider";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { AuthBridge } from "@/providers/AuthBridge";
import { RouterBridge } from "@/providers/RouterBridge";
import { TransportBridge } from "@/providers/TransportBridge";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jbm",
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "NotebookLM",
  description: "Your AI-powered research notebook.",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${jetbrainsMono.variable}`}
    >
      <head>
        {/*
         * Theme bootstrap — runs synchronously in the document head so the
         * first paint has the correct `dark` / `light` class AND
         * data-ds attribute set. Without this the SSR HTML lacks them
         * until the client effect runs, causing a flash. The script body
         * is generated by ThemeProvider so the storage keys + class names
         * stay in lock-step.
         */}
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: trusted constant */}
        <script dangerouslySetInnerHTML={{ __html: FOUC_PREVENTION_SCRIPT }} />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen antialiased">
        <ThemeProvider>
          <RouterBridge>
            <TransportBridge>
              <AuthBridge>{children}</AuthBridge>
            </TransportBridge>
          </RouterBridge>
        </ThemeProvider>
      </body>
    </html>
  );
}
